Drop legacy targets
antlr/antlr5 pull request #17
Opened 2024-01-31 08:50 UTC by ericvergnaud

Removing legacy targets, only keeping:
 - Java = reference target
 - Kotlin = source for WebAssembly
 - TypeScript = source for upcoming TypeScript wrapper (but not testing it anymore)

2024-01-31 09:53 UTC, ericvergnaud commented
Fixes #2

2024-01-31 21:54 UTC, KvanTTT requested changes
Please remove also these files:

* `.clang-formal`
* `Package.swift`
* `*.md` files in `doc` related to other targets:
  * `ace-javascript-target.md`
  * `cpp-target.md`
  * `csharp-target.md`
  * `dart-target.md`
  * `go-changes.md`
  * `go-target.md`
  * `javascript-target.md`
  * `php-target.md`
  * `python-target.md`
  * `swift-target.md`
  * `targets.md`

Also, ideally, clean-up other files with target-related things:

* `.gitignore` contains a lot of not actual lines line `runtime/Cpp/_deps/` and so on
* `.md` files in `doc` directories:
  * `creating-a-language-target.md` (something about PHP)
  * `IDEs.md` (outdated targets)
  * `interpreters.md` (something about C++)
  * `releasing-antlr.md`
  * and some other

2024-02-01 00:01 UTC, ericvergnaud commented
Updating the docs is a lot of work, and it's too early days to do that, I've created ticket #18

2024-02-01 11:24 UTC, KvanTTT approved these changes

2024-02-01 11:40 UTC, merged