first pass
antlr/antlr5 pull request #4
Opened 2024-01-17 15:23 UTC by ericvergnaud

2024-01-17 18:02 UTC, KvanTTT requested changes
Also, please fill commit message with meaningfull text. I mean `first pass` doesn't explain changes, I'd use something like this:

```
Update version info (4 -> 5) and related things

Update contributors list
Use relative links in doc where it's possible
Fix Markdown formatting
```

2024-01-17 18:02 UTC, KvanTTT commented on README.md
> +ANTLR 4 supports 10 target languages, and each of them requires a dedicated full runtime.
Please split header and paragraph by extra line break:

```suggestion
## v5 vs v4

ANTLR 4 supports 10 target languages, and each of them requires a dedicated full runtime.
```

It's a [best practice](https://www.markdownguide.org/basic-syntax/#heading-best-practices) and some Markdown rendering engines may treat line-break absense incorrectly.

2024-01-17 18:02 UTC, KvanTTT commented on README.md
>  * [Terence Parr](http://www.cs.usfca.edu/~parrt/), parrt@cs.usfca.edu
Also, please insert extra line break between paragraph and list (generally any element).

```suggestion
We're only providing here the list of ANTLR 5 contributors. ANTLR 5 is largely based on ANTLR 4. See [ANTLR 4](https://github.com/antlr/antlr4) for the list of ANTLR 4 contributors, and they are recognized as silent ANTLR 5 authors.

* [Terence Parr](http://www.cs.usfca.edu/~parrt/), parrt@cs.usfca.edu
```

2024-01-17 18:02 UTC, KvanTTT commented on README.md
> +* _Note: As WebAssembly support grows, we will expand to other mainstream languages. That said, ANTLR 5 architecture supports code generation targets as add-ons, making it easier for anyone in need t
```suggestion
* _Note: As WebAssembly supports grows, we will expand to other mainstream languages. That said, ANTLR 5 architecture supports code generation targets as add-ons, making it easier for anyone in need to support other languages without having to implement the runtime itself._
```

2024-01-17 18:02 UTC, KvanTTT commented on README.md
> +[This repository](https://github.com/antlr/grammars-v5) is a collection of grammars verified with ANTLR 5 where the
Line break:

```suggestion

[This repository](https://github.com/antlr/grammars-v5) is a collection of grammars verified with ANTLR 5 where the
```

2024-01-17 18:02 UTC, KvanTTT commented on README.md
> +ANTLR 5 project lead
No need to write it on a new line because it's soft-break and it doesn't affect the final rendering.

```suggestion
* [Eric Vergnaud](https://github.com/ericvergnaud) ANTLR 5 project lead
```

2024-01-17 18:02 UTC, KvanTTT commented on README.md
> +* [Getting started with v5](https://github.com/antlr/antlr5/blob/main/doc/getting-started.md)
Please use relative link if possible. They address correct branch (for `dev` and `main` branchs it points to actual docs in corresponding branches), works locally, and they are shorter:

```suggestion
* [Getting started with v5](doc/getting-started.md)
```

2024-01-17 18:02 UTC, KvanTTT commented on README.md
> +* [ANTLR code generation targets](https://github.com/antlr/antlr5/blob/main/doc/targets.md)<br>(Currently: TypeScript)
Relatative links:

```suggestion
* [Documentation](doc/index.md)
* [FAQ](doc/faq/index.md)
* [ANTLR code generation targets](doc/targets.md)<br>(Currently: TypeScript)
```

2024-01-17 18:02 UTC, KvanTTT commented on README.md
> +* [How we create and deploy an ANTLR release](https://github.com/antlr/antlr5/blob/main/doc/releasing-antlr.md)
```suggestion
* [How to build ANTLR itself](doc/building-antlr.md)
* [How we create and deploy an ANTLR release](doc/releasing-antlr.md)
```

2024-01-17 18:02 UTC, KvanTTT commented on README.md
> +* [v4 to v5 Migration, differences](https://github.com/antlr/antlr5/blob/main/doc/faq/general.md)
```suggestion
* [v4 to v5 Migration, differences](doc/faq/general.md)
```

2024-01-17 18:02 UTC, KvanTTT commented on doc/dart-target.md
> +[The getting started guide](https://github.com/antlr/antlr5/blob/main/doc/getting-started.md)
```suggestion
[The getting started guide](doc/getting-started.md) 
```

2024-01-17 18:02 UTC, KvanTTT commented on doc/dart-target.md
> +as described in [the getting started guide](https://github.com/antlr/antlr5/blob/main/doc/getting-started.md).
```suggestion
as described in [the getting started guide](../doc/getting-started.md). 
```

2024-01-17 18:02 UTC, KvanTTT commented on doc/dart-target.md
> +[tool documentation page](https://github.com/antlr/antlr5/blob/main/doc/tool-options.md).
```suggestion
[tool documentation page](../doc/tool-options.md).
```

2024-01-17 18:02 UTC, KvanTTT commented on doc/faq/general.md
> +ANTLR 4 automatically constructs parse trees for you and abstract syntax tree (AST) construction is no longer an option. See also [What if I need ASTs not parse trees for a compiler, for example?](ht
```suggestion
ANTLR 4 automatically constructs parse trees for you and abstract syntax tree (AST) construction is no longer an option. See also [What if I need ASTs not parse trees for a compiler, for example?](parse-trees.md#what-if-i-need-asts-not-parse-trees-for-a-compiler-for-example).
```

2024-01-17 18:02 UTC, KvanTTT commented on doc/faq/general.md
> +Another big difference is that we discourage the use of actions directly within the grammar because ANTLR 4 automatically generates [listeners and visitors](https://github.com/antlr/antlr5/blob/main/
```suggestion
Another big difference is that we discourage the use of actions directly within the grammar because ANTLR 4 automatically generates [listeners and visitors](../listeners.md) for you to use that trigger method calls when some phrases of interest are recognized during a tree walk after parsing. See also [Parse Tree Matching and XPath](../tree-matching.md).
```

2024-01-17 18:02 UTC, KvanTTT commented on doc/getting-started.md
> +If you are going to integrate ANTLR into your existing build system using mvn, ant, or want to get ANTLR into your IDE such as eclipse or intellij, see [Integrating ANTLR into Development Systems](ht
```suggestion
If you are going to integrate ANTLR into your existing build system using mvn, ant, or want to get ANTLR into your IDE such as eclipse or intellij, see [Integrating ANTLR into Development Systems](IDEs.md).
```

2024-01-17 18:02 UTC, KvanTTT commented on doc/parser-rules.md
> +The args, locals, and return `[...]` are generally in the target language but with some constraints. The `[...]` string is a comma-separated list of declarations either with prefix or postfix type no
```suggestion
The args, locals, and return `[...]` are generally in the target language but with some constraints. The `[...]` string is a comma-separated list of declarations either with prefix or postfix type notation or no-type notation. The elements can have initializer such as `[int x = 32, float y]` but don't go too crazy as we are parsing this generic text manually in [ScopeParser](../tool/src/org/antlr/v4/parse/ScopeParser.java).  
```

2024-01-17 18:02 UTC, KvanTTT commented on doc/parser-rules.md
> +Technically any target could use either notation. For examples, see [TestScopeParsing](https://github.com/antlr/antlr5/blob/main/tool-testsuite/test/org/antlr/v4/test/tool/TestScopeParsing.java).
```suggestion
Technically any target could use either notation. For examples, see [TestScopeParsing](../tool-testsuite/test/org/antlr/v4/test/tool/TestScopeParsing.java).
```

2024-01-17 18:02 UTC, KvanTTT commented on doc/php-target.md
> +[The getting started guide](https://github.com/antlr/antlr5/blob/main/doc/getting-started.md)
```suggestion
[The getting started guide](getting-started.md) 
```

2024-01-17 18:02 UTC, KvanTTT commented on doc/php-target.md
> +as described in [the getting started guide](https://github.com/antlr/antlr5/blob/main/doc/getting-started.md).
```suggestion
as described in [the getting started guide](getting-started.md). 
```

2024-01-17 18:02 UTC, KvanTTT commented on doc/php-target.md
> +[tool documentation page](https://github.com/antlr/antlr5/blob/main/doc/tool-options.md).
```suggestion
[tool documentation page](tool-options.md).
```

2024-01-17 18:02 UTC, KvanTTT commented on doc/python-target.md
> +_For a list of antlr4 tool options, please visit [ANTLR Tool Command Line Options](https://github.com/antlr/antlr5/blob/main/doc/tool-options.md)._
```suggestion
_For a list of antlr4 tool options, please visit [ANTLR Tool Command Line Options](tool-options.md)._
```

2024-01-17 18:02 UTC, KvanTTT commented on doc/tree-matching.md
> +See [TestParseTreeMatch.java](https://github.com/antlr/antlr5/blob/main/tool-testsuite/test/org/antlr/v4/test/tool/TestParseTreeMatcher.java).
```suggestion
See [TestParseTreeMatch.java](../tool-testsuite/test/org/antlr/v4/test/tool/TestParseTreeMatcher.java).
```

2024-01-17 18:02 UTC, KvanTTT commented on doc/tree-matching.md
> +See [TestXPath.java](https://github.com/antlr/antlr5/blob/main/tool-testsuite/test/org/antlr/v4/test/tool/TestXPath.java).
```suggestion
See [TestXPath.java](../tool-testsuite/test/org/antlr/v4/test/tool/TestXPath.java).
```

2024-01-17 18:02 UTC, KvanTTT commented on pom.xml
> +            <url>https://github.com/kvantt</url>
Misprint:

```suggestion
            <url>https://github.com/kvanttt</url>
```

2024-01-17 18:02 UTC, KvanTTT commented on runtime/Dart/README.md
> +See https://github.com/antlr/antlr5/blob/main/doc/dart-target.md for more information on using ANTLR in Dart.
```suggestion
See [dart-target.md](../../doc/dart-target.md) for more information on using ANTLR in Dart.
```

2024-01-17 18:02 UTC, KvanTTT commented on runtime/JavaScript/README.md
> +See [Javascript Target](https://github.com/antlr/antlr5/blob/main/doc/javascript-target.md)
```suggestion
See [Javascript Target](../../doc/javascript-target.md)
```

2024-01-17 18:44 UTC, ericvergnaud commented on README.md
> +* _Note: As WebAssembly support grows, we will expand to other mainstream languages. That said, ANTLR 5 architecture supports code generation targets as add-ons, making it easier for anyone in need t
Sorry I believe the original wording is correct.

2024-01-17 21:52 UTC, ericvergnaud commented
I've reached a state where it compiles - no attempts to test
Merging so it can be used by other contributors
Partially fixes #3

2024-01-17 21:57 UTC, merged

2024-01-17 22:05 UTC, KvanTTT commented
Sorry, but could you please wait for approvement from at least one member next time?

Also, please use git squashing next time to get rid of useless commits (or squash/edit them manually). Now I see a lot of non-informative commits in antlr5 history instead of one meaningful commit.

I don't understand why we are rushing.

2024-01-17 22:27 UTC, ericvergnaud commented
Hey, ok to squash in the future. 
I'm just making sure we rapidly reach a situation where people can start contributing on a viable basis, which is where we are now i.e. the project compiles.

2024-01-18 16:25 UTC, KvanTTT commented
> Hey, ok to squash in the future.

Thanks.

> I'm just making sure we rapidly reach a situation where people can start contributing on a viable basis, which is where we are now i.e. the project compiles.

I don't think changing version number affects users' contributions and experience. Project was compilable before this change.